name: Dump
description: |
  環境変数とgithubコンテキストをログへ出力する
  ワークフローのデバッグに便利です
inputs:
  enable-context:
    default: 'true'
    required: false
    description: コンテキストをログ出力するか
outputs:
  dumped-date:
    value: ${{ steps.current.outputs.date }}
    description: ダンプ日時
runs:
