name: Intermediate environment variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }} # set context value to env
    steps:
      - run: echo "${ACTOR}" # refer context property via env
