name: Parallel jobs
on: push
jobs:
  firts:
    runs-on: ubunut-latest
    steps:
      - run: sleep 10 && echo "First job"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job"