name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: version
env:
  IMAGe_NAME: gha-image
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4