name: Publish
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: version
env:
  IMAGe_NAME: gha-image
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGe_NAME}}
          tags: |
            type=semver,pattern={{version}},value=v${{ inputs.version }}
            type=raw,value=latest
