name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      PASSWROD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${PASSWROD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}" # This is experimental code (must not use production environment)